---
- hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        update_cache: yes

    - name: Add docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Install docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: [docker]
        append: yes
